version: "3.3"

services:

  wallet_api_db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=9800
      - PGDATA=/var/lib/postgresql/data/pgdata

  # wallet_payment_db:
  #   image: postgres:13
  #   restart: always
  #   envfiles:
  #     - "./projects/WalletPaymentService/.env"

  app_event_bus:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=admin1234

  wallet_api_service:
    build:
      context: ./projects/WalletAPIService
      dockerfile: Dockerfile
    env_file:
      - "./projects/WalletAPIService/.env"
    depends_on:
      - wallet_api_db
      - app_event_bus
    restart: always

    volumes:
      - ./projects/WalletAPIService:/app