# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: wallet-api-service
  namespace: default
spec:
  selector:
    app: wallet-api-service
  type: LoadBalancer
  ports:
  - name: wallet-api-service
    protocol: TCP
    port: 8000
---